### ISSUE TITLE
First iteration of pickup mechanic

### ISSUE THREAD

**Issue by leohlim** [leohlim/MetroidvaniaJam#5]
**Description**
A pickup/placement mechanic

**Conditions of satisfaction**
- [x] A tag system for items that can be picked up.
- [x] Items with interactable tag can be picked up (item hovers in center front of the player)
- [x] Player can move around with the item in front of them.
- [x] Player can drop the item by clicking left mouse button (uses physics)
- [x] Player can "snap" item into a trigger box (like a battery in a battery holder) by pressing left mouse button
- [x] Item does not clip when against the wall.

**Comment by severn2** [comment]
Completed. 5/13/20
